### ISSUE TITLE
Make identifiable a report when it is opened

### ISSUE THREAD

**Issue by Rumengol** [BAUDOTlab/scDataPipeline#55]
We always wonder which dataset we are looking at. We maybe need to change the Rmarkdown theme.
see the [rmdformats package](https://bookdown.org/yihui/rmarkdown/rmdformats.html) with the material theme ???

Morgane shared this part of the YAML header of the Rmd file.
```
---
title: ""
author: ""
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output:
  rmdformats::material:
    use_bookdown: true
    thumbnails: false
    css: "ETBII_SNF.css"
header-includes:
  - \usepackage{subfig}
  - \usepackage{booktabs}
  - \usepackage{xcolor}
  - \usepackage{tcolorbox}
---
```
