### ISSUE TITLE
Change the DATASET field in combine config file

### ISSUE THREAD

**Issue by Rumengol** [BAUDOTlab/scDataPipeline#97]
The way it is currently written makes it unclear which dataset is the reference and which is the control. The field

```toml
DATASET = "XXX"
```

Should be changed to 

```toml
REFERENCE_DATASET = "XXX"
CONDITION_DATASETS = ["XXX","XXX"] # There can be multiple conditions for an analysis, but only one reference.
````
